//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNhaHang
    {
        public int MaThongTin { get; set; }
        public int NguoiDang { get; set; }
        public string URLMap { get; set; }
        public string TenNhaHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai1 { get; set; }
        public string SoDienThoai2 { get; set; }
        public string ThongTinKhac { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
