//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDung
    {
        public int MaTuyenDung { get; set; }
        public string TenTuyenDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string ChiTiet { get; set; }
        public int NguoiDang { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
